# Dockerfile.frontend

# 1. Указываем базовый образ
FROM node:18

# 2. Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# 3. Копируем package.json и package-lock.json для установки зависимостей
COPY ./frontend/package*.json ./

# 4. Устанавливаем зависимости
RUN npm install

# 5. Копируем все файлы из папки фронтенда в рабочую директорию контейнера
COPY ./frontend .

# 6. Запускаем React-приложение
CMD ["npm", "start"]